name: tfgrid-gitea
version: 0.1.0
description: Self-hosted Git service with web interface

# Pattern compatibility
patterns:
  recommended: single-vm
  supported:
    - single-vm
    # Future: - gateway

# Resource requirements
resources:
  cpu:
    min: 2
    recommended: 2
  memory:
    min: 2048
    recommended: 4096
  disk:
    min: 25
    recommended: 50
  ports:
    - 22:ssh
    - 3000:http  # Gitea web interface

# System dependencies
dependencies:
  system:
    - git
    - curl
    - sqlite3  # For database
  external:
    - gitea: ">=1.21.0"

# Deployment hooks (called by deployer)
hooks:
  setup: deployment/setup.sh
  configure: deployment/configure.sh
  healthcheck: deployment/healthcheck.sh

# Environment variables (optional)
environment:
  - name: GITEA_ADMIN_USER
    default: gitadmin
    description: "Admin username"
  - name: GITEA_ADMIN_PASSWORD
    default: changeme123
    secret: true
    description: "Admin password (change immediately)"
  - name: GITEA_ADMIN_EMAIL
    default: admin@localhost
    description: "Admin email"
  - name: GITEA_DOMAIN
    description: "Domain for gateway deployment"

# Logging configuration
logging:
  method: systemd
  service: gitea
  location: /var/log/gitea

# Status check
status:
  method: systemd
  service: gitea

# App-specific commands (v0.11.0+)
commands:
  init:
    script: /opt/gitea/scripts/init-admin.sh
    description: Initialize admin user
  launch:
    script: /opt/gitea/scripts/launch.sh
    description: Open Gitea web interface in browser

  # Repository management
  create-repo:
    script: /opt/gitea/scripts/create-repo.sh
    description: Create a new repository
    args: "<repo-name> [--private] [--description='desc']"
    interactive: true
  list-repos:
    script: /opt/gitea/scripts/list-repos.sh
    description: List all repositories
  delete-repo:
    script: /opt/gitea/scripts/delete-repo.sh
    description: Delete a repository
    args: "<repo-name> [--confirm]"
    interactive: true

  # User management
  create-user:
    script: /opt/gitea/scripts/create-user.sh
    description: Create a new user
    args: "<username> <email> [--admin]"
    interactive: true
  list-users:
    script: /opt/gitea/scripts/list-users.sh
    description: List all users
  reset-password:
    script: /opt/gitea/scripts/reset-password.sh
    description: Reset user password
    args: "<username>"
    interactive: true

  # Git operations
  clone-repo:
    script: /opt/gitea/scripts/clone-repo.sh
    description: Clone a repository locally
    args: "<repo-name> [local-path]"
  push-code:
    script: /opt/gitea/scripts/push-code.sh
    description: Push code to a repository
    args: "<repo-name> <local-path> [--force]"

  # Administrative
  backup:
    script: /opt/gitea/scripts/backup.sh
    description: Create backup
    args: "[backup-name]"
  restore:
    script: /opt/gitea/scripts/restore.sh
    description: Restore from backup
    args: "<backup-file>"
  status:
    script: /opt/gitea/scripts/status.sh
    description: Service status
